Test Build

diff --git a/Dockerfile-linux b/Dockerfile-linux
--- a/Dockerfile-linux
+++ b/Dockerfile-linux
@@ -32,8 +32,8 @@ ENV HOST=x86_64-pc-linux-gnu
 # Download depends
 RUN mkdir -p $PROJECTDIR \
   && cd $PROJECTDIR \
-  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v4.2.0-lin-bionic.tar.gz \
-  && [ "$(printf '547e4bdabc132b189cc78d6a12093f4476b6a49dc293b8371f2a046f6c3ecdb9 depends-v4.2.0-lin-bionic.tar.gz' | sha256sum -c)" = "depends-v4.2.0-lin-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+  && wget -nv https://github.com/mraksoll4/docker-build-depends/releases/download/v1.0.1/depends-v1.0.1-lin-bionic.tar.gz \
+  && [ "$(printf '25b55f9d5628ee9719f89202007d15ec9af5a9f9cd0e348cf6270e9e4bf5e022 depends-v1.0.1-lin-bionic.tar.gz' | sha256sum -c)" = "depends-v1.0.1-lin-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
 
 # Copy source files
 COPY . $PROJECTDIR/
@@ -42,7 +42,7 @@ COPY . $PROJECTDIR/
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
   && rm -r $BASEPREFIX \
-  && tar xzf depends-v4.2.0-lin-bionic.tar.gz \
+  && tar xzf depends-v1.0.1-lin-bionic.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CC=gcc-8 CXX=g++-8 CFLAGS="-g3 -O0" CXXFLAGS="-g3 -O0" --enable-debug --prefix=/ \
diff --git a/Dockerfile-mac b/Dockerfile-mac
--- a/Dockerfile-mac
+++ b/Dockerfile-mac
@@ -34,8 +34,8 @@ ENV HOST=x86_64-apple-darwin14
 # Download depends
 RUN mkdir -p $PROJECTDIR \
   && cd $PROJECTDIR \
-  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v4.2.0-mac-bionic.tar.gz \
-  && [ "$(printf 'f1c92dbbcc4f2e05e5965a7031993e8e0f6e38fee987f30e98ae9a65c7d255b9 depends-v4.2.0-mac-bionic.tar.gz' | sha256sum -c)" = "depends-v4.2.0-mac-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+  && wget -nv https://github.com/mraksoll4/docker-build-depends/releases/download/v1.0.1/depends-v1.0.1-mac-bionic.tar.gz \
+  && [ "$(printf '7a0508f0e1bdb44cc86ce589da628264790b391f59f5159fcfb89e360c30f9b4 depends-v1.0.1-mac-bionic.tar.gz' | sha256sum -c)" = "depends-v1.0.1-mac-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
 
 # Copy source files
 COPY . $PROJECTDIR/
@@ -44,7 +44,7 @@ COPY . $PROJECTDIR/
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
   && rm -r $BASEPREFIX \
-  && tar xzf depends-v4.2.0-mac-bionic.tar.gz \
+  && tar xzf depends-v1.0.1-mac-bionic.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CFLAGS="-g3 -O0" CXXFLAGS="-g3 -O0" --with-gui=qt5 --enable-debug --prefix=/ \
diff --git a/Dockerfile-win b/Dockerfile-win
--- a/Dockerfile-win
+++ b/Dockerfile-win
@@ -33,8 +33,8 @@ ENV HOST=x86_64-w64-mingw32
 # Download depends
 RUN mkdir -p $PROJECTDIR \
   && cd $PROJECTDIR \
-  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v4.2.0-win-bionic.tar.gz \
-  && [ "$(printf '1a10012c4fd13cc1eb671ac5a3919cd42c86b9ff90f875ce8fa153a77871170c depends-v4.2.0-win-bionic.tar.gz' | sha256sum -c)" = "depends-v4.2.0-win-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+  && wget -nv https://github.com/mraksoll4/docker-build-depends/releases/download/v1.0.1/depends-v1.0.1-win-bionic.tar.gz \
+  && [ "$(printf '8ff9381acafd93d49619dffa9e462a3e2cc895f500562d8ac0420d40563b965d depends-v1.0.1-win-bionic.tar.gz' | sha256sum -c)" = "depends-v1.0.1-win-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
 
 # Copy source files
 COPY . $PROJECTDIR/
@@ -43,7 +43,7 @@ COPY . $PROJECTDIR/
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
   && rm -r $BASEPREFIX \
-  && tar xzf depends-v4.2.0-win-bionic.tar.gz \
+  && tar xzf depends-v1.0.1-win-bionic.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --enable-reduce-exports --disable-bench --disable-gui-tests \
